### ISSUE TITLE
Change Manage Property Alias

### ISSUE THREAD

**Issue by gsari** [wobba/SearchConfiguration#1]
Hi,

Thank you for sharing this script (MapCrawledPropertyToManagedProperty.ps1)
Is it possible, when you map a Refinable Managed Property, by using you script, to update Managed Property's Alias also?
Is there any other attibute in XML file, (SearchMappingTemplate.xml) that we can use to add alias name?

Thank you
George

**Comment by wobba** [comment]
If you add an alias to a property and export the search config, you should find out where the Alias should go in the xml and make that change. Let me know if you manage to add it and I'll be happy to update my script.

**Comment by gsari** [comment]
Thank you Michael,
I'll try and let you know.

George

**Comment by gsari** [comment]
[SearchMappingTemplate1.zip](https://github.com/wobba/SearchConfiguration/files/9542944/SearchMappingTemplate1.zip)
@wobba hi,
I attatching the updated xml file, with the "Alias" part. 
If you want to update your script, add:
   1) New parapmeter for mapping Alias
   2) The ##ALIASNAME## reference. 

Can you please help me with the following:
I'm also trying to run the "reset" mode of your script, but nothing is happened. After running the script, the Mangaged Property mappings are still there.
Is the reset part working well for you? 
Is there somehing that i should change?
I'm just follow your intructions from your script.

Thanks again for sharing this script.

George

**Comment by wobba** [comment]
Reset worked when I created the script but haven't tried it lately. I'll try to get some time to re-test it.

**Comment by wobba** [comment]
@gsari can you provide the update to the powershell script as well?

**Comment by gsari** [comment]
@wobba hi,

Please check line 158

[MapCrawledPropertyToManagedProperty_v1.zip](https://github.com/wobba/SearchConfiguration/files/9746187/MapCrawledPropertyToManagedProperty_v1.zip)

George

**Comment by wobba** [comment]
Decided to drop it as you should change the config more if an alias is not provided. And seems import of xml files are buggy these days as well :(
