### ISSUE TITLE
Crawl time trick does not seems to be working

### ISSUE THREAD

**Issue by stevebeauge** [wobba/SearchConfiguration#3]
In the past, I used to import https://github.com/wobba/SearchConfiguration/blob/master/CrawlTimeSchema.xml to facilitate the diagnostic of search engine issues. It was working as expected.

However, the latest use of this mappings, whether it's imported from pnp powershell, from the GUI or manually recreating the mapping, does not seems to work.

CrawlTime managed property is always empty.

Is this trick still supposed to be working ?

I tried at least on 4 different tenants.

Any suggestion?

thanks

**Comment by wobba** [comment]
Hi, I believe checking the crawl log is your best option these days.

**Comment by stevebeauge** [comment]
OK

I guess I should close the issue here since it's not your config in cause.

Thanks

**Comment by wobba** [comment]
The feature was never documented and backend things has likely changed which is why it's not populated 😞

**Comment by stevebeauge** [comment]
Maybe you should edit the README.md file of this repo to let us know it's no more working ?

**Comment by wobba** [comment]
Done..added that it's for onprem only....as I assume that still works.
